"""FastAPI scoring service for the SLA-breach model.

Runtime footprint: ``slawatch.model`` (numpy, pandas, scikit-learn, pydantic) and FastAPI.
No database, no training code. The artifact and its model card are loaded once, when the
application object is created (process start locally, function init on Lambda), and the
process refuses to start if either is missing or if the card does not describe the artifact.

Configuration (environment variables):

* ``SLAWATCH_MODEL_PATH``      path to ``sla_breach.joblib`` (default: ``models/`` in the repo)
* ``SLAWATCH_MODEL_CARD_PATH`` path to ``model_card.json`` (default: next to the artifact)

Run locally with ``make serve`` (uvicorn) or wrap with Mangum (``slawatch.lambda_handler``).
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated, Any

from fastapi import Body, FastAPI, Request
from pydantic import BaseModel, Field

from slawatch import __version__
from slawatch import model as M

BATCH_MAX = 500
"""Maximum tickets per ``POST /v1/score/batch`` request (a larger body is a 422)."""

SYNTHETIC_NOTE = (
    "The model behind this API was trained on **synthetic** trouble-ticket data generated by "
    "`slawatch-generate` (TMF621-shaped, seeded). Its probabilities describe that synthetic "
    "world, not any real service desk; see `docs/model.md` in the repository."
)

EXAMPLE_TICKET: dict[str, Any] = {
    "ticket_type": "incident",
    "severity": "major",
    "channel": "email",
    "tier": "gold",
    "industry": "retail",
    "region": "ontario",
    "province": "ON",
    "service_type": "sd_wan",
    "assignment_group": "field_ontario",
    "customer_id": "cust-001",
    "priority": 2,
    "open_backlog_at_creation": 40,
    "sla_target_hours": 12.0,
    "creation_hour_local": 22,
    "creation_dow_local": 6,
    "has_active_outage": True,
    "is_weekend": True,
    "is_after_hours": True,
    "has_requested_resolution_date": False,
}
EXAMPLE_CALM_TICKET: dict[str, Any] = {
    **EXAMPLE_TICKET,
    "channel": "monitoring",
    "open_backlog_at_creation": 5,
    "creation_hour_local": 10,
    "creation_dow_local": 1,
    "has_active_outage": False,
    "is_weekend": False,
    "is_after_hours": False,
}


# ------------------------------------------------------------------------------------------
# Settings
# ------------------------------------------------------------------------------------------
@dataclass(frozen=True)
class Settings:
    model_path: Path = M.DEFAULT_MODEL_PATH
    card_path: Path | None = None  # None -> <model_path dir>/model_card.json

    @classmethod
    def from_env(cls) -> Settings:
        model_path = Path(os.environ.get("SLAWATCH_MODEL_PATH", M.DEFAULT_MODEL_PATH))
        card = os.environ.get("SLAWATCH_MODEL_CARD_PATH")
        return cls(model_path=model_path, card_path=Path(card) if card else None)

    @property
    def resolved_card_path(self) -> Path:
        return self.card_path or self.model_path.parent / "model_card.json"


# ------------------------------------------------------------------------------------------
# Response schemas
# ------------------------------------------------------------------------------------------
class TrainingWindow(BaseModel):
    first_month: str = Field(description="First calendar month of the training split (YYYY-MM).")
    last_month: str = Field(description="Last calendar month of the training split (YYYY-MM).")


class HealthResponse(BaseModel):
    status: str = Field(description='"ok" once the model and its card are loaded.')
    service_version: str = Field(description="slawatch package version.")
    model_version: str = Field(description="`model_version` from the model card.")
    trained_at: str | None = Field(description="Training timestamp (UTC, ISO 8601).")
    training_window: TrainingWindow | None = Field(
        description="Calendar months the model was fitted on (synthetic data)."
    )
    synthetic_data: bool = Field(description="Always true for this project.")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "status": "ok",
                    "service_version": "0.1.0",
                    "model_version": "0.1.0",
                    "trained_at": "2026-09-16T19:38:15+00:00",
                    "training_window": {"first_month": "2024-07", "last_month": "2025-12"},
                    "synthetic_data": True,
                }
            ]
        }
    }


class ScoreResult(BaseModel):
    probability: float = Field(
        ge=0, le=1, description="Calibrated P(SLA breach) for the ticket, rounded to 6 places."
    )
    risk_band: str = Field(
        description="`low` < medium band threshold <= `medium` < high band threshold <= `high`."
    )
    flag_for_review: bool = Field(
        description="`probability >= threshold`; the threshold is set so that about the "
        "riskiest 10% of validation tickets are flagged."
    )


class ScoreResponse(ScoreResult):
    threshold: float = Field(description="Review threshold in use (from the model card).")
    model_version: str = Field(description="`model_version` from the model card.")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "probability": 0.756159,
                    "risk_band": "high",
                    "flag_for_review": True,
                    "threshold": 0.263431,
                    "model_version": "0.1.0",
                }
            ]
        }
    }


class BatchScoreRequest(BaseModel):
    tickets: list[M.TicketFeatures] = Field(
        min_length=1,
        max_length=BATCH_MAX,
        description=f"1 to {BATCH_MAX} tickets; results come back in the same order.",
    )


class BatchScoreResponse(BaseModel):
    results: list[ScoreResult] = Field(description="One result per input ticket, same order.")
    count: int = Field(description="Number of tickets scored.")
    threshold: float = Field(description="Review threshold in use (from the model card).")
    model_version: str = Field(description="`model_version` from the model card.")


# ------------------------------------------------------------------------------------------
# App factory
# ------------------------------------------------------------------------------------------
def load_runtime(settings: Settings) -> tuple[M.LoadedModel, dict[str, Any]]:
    """Load the artifact and verify the model card describes it. Raises on any problem."""
    model = M.load_model(settings.model_path)
    card_path = settings.resolved_card_path
    if not card_path.exists():
        raise FileNotFoundError(
            f"model card not found at {card_path}; set SLAWATCH_MODEL_CARD_PATH or run `make train`"
        )
    card = M.check_card(model, card_path, settings.model_path)
    return model, card


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or Settings.from_env()
    model, card = load_runtime(settings)

    app = FastAPI(
        title="slawatch scoring API",
        version=__version__,
        summary="P(SLA breach) for an enterprise trouble ticket at creation time.",
        description=(
            "Scores trouble tickets with the slawatch SLA-breach classifier using only "
            "features known when the ticket is created.\n\n"
            f"> **Synthetic data.** {SYNTHETIC_NOTE}\n\n"
            f"Model version **{card['model_version']}**, trained {card.get('trained_at')} "
            f"(scikit-learn {card.get('sklearn_version')}). The full model card is served at "
            "`GET /v1/model`. Categorical values are case-insensitive; unknown fields "
            "(including any outcome column such as `sla_breached`) are rejected with 422."
        ),
        license_info={"name": "MIT"},
        openapi_tags=[
            {"name": "service", "description": "Liveness and model metadata."},
            {"name": "scoring", "description": "Score one ticket or a batch."},
        ],
    )
    app.state.settings = settings
    app.state.model = model
    app.state.card = card

    def _model(request: Request) -> M.LoadedModel:
        return request.app.state.model

    def _results(loaded: M.LoadedModel, tickets: list[M.TicketFeatures]) -> list[ScoreResult]:
        return [
            ScoreResult(
                probability=r["probability"],
                risk_band=r["risk_band"],
                flag_for_review=r["probability"] >= loaded.threshold,
            )
            for r in M.score(tickets, model=loaded)
        ]

    @app.get("/health", response_model=HealthResponse, tags=["service"], summary="Liveness")
    def health(request: Request) -> HealthResponse:
        """Reports that the model and its card are loaded, with the model version and the
        calendar window of the (synthetic) training data."""
        card = request.app.state.card
        train_split = card.get("data", {}).get("split", {}).get("train")
        return HealthResponse(
            status="ok",
            service_version=__version__,
            model_version=str(card["model_version"]),
            trained_at=card.get("trained_at"),
            training_window=TrainingWindow(**train_split) if train_split else None,
            synthetic_data=bool(card.get("synthetic_data", True)),
        )

    @app.get(
        "/v1/model",
        tags=["service"],
        summary="Model card",
        response_description="`models/model_card.json` as committed with the artifact.",
    )
    def model_card(request: Request) -> dict[str, Any]:
        """The model card: version, estimator and hyperparameters, feature contract with
        allowed values, categorical levels seen in training, thresholds, held-out test
        metrics and the synthetic data window. This is the same file that documents the
        model in the repository; the service verified at startup that it matches the loaded
        artifact."""
        return request.app.state.card

    @app.post(
        "/v1/score",
        response_model=ScoreResponse,
        tags=["scoring"],
        summary="Score one ticket",
        responses={422: {"description": "Invalid or unknown field, level or range."}},
    )
    def score_one(
        request: Request,
        ticket: Annotated[
            M.TicketFeatures,
            Body(
                openapi_examples={
                    "weekend_outage": {
                        "summary": "Major incident, weekend night, during a regional outage",
                        "value": EXAMPLE_TICKET,
                    },
                    "quiet_business_hours": {
                        "summary": "Same ticket on a quiet weekday morning",
                        "value": EXAMPLE_CALM_TICKET,
                    },
                }
            ),
        ],
    ) -> ScoreResponse:
        """Returns the breach probability, its risk band, whether it crosses the review
        threshold, the threshold used and the model version."""
        loaded = _model(request)
        (result,) = _results(loaded, [ticket])
        return ScoreResponse(
            **result.model_dump(), threshold=loaded.threshold, model_version=loaded.version
        )

    @app.post(
        "/v1/score/batch",
        response_model=BatchScoreResponse,
        tags=["scoring"],
        summary=f"Score up to {BATCH_MAX} tickets",
        responses={
            422: {
                "description": f"Empty list, more than {BATCH_MAX} tickets, or any invalid ticket "
                "(the whole batch is rejected; `loc` names the offending index and field)."
            }
        },
    )
    def score_batch(
        request: Request,
        body: Annotated[
            BatchScoreRequest,
            Body(
                openapi_examples={
                    "two_tickets": {
                        "summary": "Two tickets",
                        "value": {"tickets": [EXAMPLE_TICKET, EXAMPLE_CALM_TICKET]},
                    }
                }
            ),
        ],
    ) -> BatchScoreResponse:
        """Scores the tickets in one model call and returns results in input order. The cap
        keeps a single Lambda invocation well inside its time and payload limits."""
        loaded = _model(request)
        results = _results(loaded, body.tickets)
        return BatchScoreResponse(
            results=results,
            count=len(results),
            threshold=loaded.threshold,
            model_version=loaded.version,
        )

    return app


app = create_app()
