"""Weekly service-desk KPI report as an Excel workbook, from the PostgreSQL views.

Usage:
    uv run slawatch-report                                  # last full week -> reports/
    uv run slawatch-report --week-ending 2026-06-28 --out reports/kpi.xlsx
    uv run slawatch-report --top-n 100                      # longer at-risk list

The workbook is live: the Summary tiles and every derived column are Excel formulas over the
numbers copied from ``v_weekly_kpi`` and friends, so a reader can trace each figure. Every
sheet is labelled synthetic; there is no real customer or ticket anywhere in the data.
"""

from __future__ import annotations

import argparse
import logging
from dataclasses import dataclass
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal
from pathlib import Path
from typing import Any

import pandas as pd
from openpyxl import Workbook
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.formatting.rule import CellIsRule, ColorScaleRule, DataBarRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet
from sqlalchemy import Engine, text

from slawatch import __version__, db
from slawatch.labels import SERVICE_LABELS, group_label

log = logging.getLogger("slawatch.report")

SYNTHETIC_BANNER = "SYNTHETIC DATA - generated by slawatch; no real customers, sites or tickets"
TREND_WEEKS = 13  # rows in the Summary trend table (report week last)
BASELINE_WEEKS = 4  # trailing average = the four weeks before the report week
DEFAULT_TOP_N = 50
DEFAULT_REPORTS_DIR = Path("reports")

AGE_BUCKETS = ["0-24h", "1-3d", "3-7d", "7-30d", "30d+"]

# Formats and styles ----------------------------------------------------------------------
FMT_INT = "#,##0"
FMT_HOURS = "0.0"
FMT_PCT = "0.0%"
FMT_PP = '+0.0" pp";-0.0" pp";0.0" pp"'
FMT_DELTA_INT = "+#,##0;-#,##0;0"
FMT_DELTA_HOURS = "+0.0;-0.0;0.0"
FMT_PROB = "0.000"
FMT_DATE = "yyyy-mm-dd"
FMT_DATETIME = "yyyy-mm-dd hh:mm"

TITLE_FONT = Font(bold=True, size=14)
SUBTITLE_FONT = Font(italic=True, size=10, color="555555")
BANNER_FONT = Font(bold=True, color="9C0006")
HEADER_FONT = Font(bold=True, color="FFFFFF")
HEADER_FILL = PatternFill("solid", fgColor="1F4E78")
TOTAL_FONT = Font(bold=True)
TOTAL_FILL = PatternFill("solid", fgColor="DDEBF7")
GOOD_FILL = PatternFill("solid", fgColor="C6EFCE")
BAD_FILL = PatternFill("solid", fgColor="FFC7CE")
GOOD_FONT = Font(color="006100")
BAD_FONT = Font(color="9C0006")
THIN = Side(style="thin", color="BFBFBF")
BOX = Border(top=THIN, bottom=THIN, left=THIN, right=THIN)


# ------------------------------------------------------------------------------------------
# Data
# ------------------------------------------------------------------------------------------
@dataclass
class ReportData:
    week_ending: date
    week_start: date
    as_of: datetime  # backlog snapshot = Monday 00:00 UTC after the week
    trend: pd.DataFrame  # v_weekly_kpi, the TREND_WEEKS weeks ending with the report week
    by_customer: pd.DataFrame
    by_service: pd.DataFrame
    open_tickets: pd.DataFrame  # f_open_tickets(as_of)
    at_risk: pd.DataFrame  # top-N of open_tickets by probability
    snapshot_ts: datetime
    model_version: str | None
    generated_at: datetime
    source: str


def _query(engine: Engine, sql: str, **params: Any) -> pd.DataFrame:
    with engine.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params or None)


def available_weeks(engine: Engine) -> list[date]:
    weeks = _query(engine, "SELECT week_ending FROM v_weekly_kpi ORDER BY week_ending")
    return [pd.Timestamp(w).date() for w in weeks["week_ending"]]


def default_week_ending(engine: Engine) -> date:
    """The last full Monday-Sunday week before the load snapshot."""
    weeks = available_weeks(engine)
    if not weeks:
        raise SystemExit("v_weekly_kpi is empty: is the database loaded? (make load)")
    return weeks[-1]


def parse_week_ending(value: str) -> date:
    try:
        d = date.fromisoformat(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"{value!r} is not a YYYY-MM-DD date") from exc
    if d.weekday() != 6:
        raise argparse.ArgumentTypeError(f"{value} is not a Sunday; weeks run Monday to Sunday")
    return d


def _to_naive_utc(s: pd.Series) -> pd.Series:
    s = pd.to_datetime(s, utc=True)
    return s.dt.tz_convert("UTC").dt.tz_localize(None)


def fetch(
    engine: Engine, week_ending: date | None = None, top_n: int = DEFAULT_TOP_N
) -> ReportData:
    weeks = available_weeks(engine)
    if not weeks:
        raise SystemExit("v_weekly_kpi is empty: is the database loaded? (make load)")
    week_ending = week_ending or weeks[-1]
    if week_ending not in weeks:
        raise SystemExit(
            f"no full week ends on {week_ending}; available weeks end {weeks[0]} to {weeks[-1]}"
        )
    if weeks.index(week_ending) < 1:
        raise SystemExit(f"{week_ending} is the first week in the data; nothing to compare with")

    trend = _query(
        engine,
        """
        SELECT * FROM (
            SELECT * FROM v_weekly_kpi WHERE week_ending <= :w ORDER BY week_ending DESC LIMIT :n
        ) t ORDER BY week_ending
        """,
        w=week_ending,
        n=TREND_WEEKS,
    )
    prior_week = week_ending - timedelta(days=7)
    by_customer = _query(
        engine,
        """
        SELECT cur.*,
               prev.sla_compliance_pct AS prior_week_compliance_pct
        FROM v_weekly_kpi_by_customer cur
        LEFT JOIN v_weekly_kpi_by_customer prev
               ON prev.customer_id = cur.customer_id AND prev.week_ending = :p
        WHERE cur.week_ending = :w
        ORDER BY cur.breached_tickets DESC, cur.tickets_opened DESC, cur.customer_name
        """,
        w=week_ending,
        p=prior_week,
    )
    by_service = _query(
        engine,
        """
        SELECT cur.*,
               prev.sla_compliance_pct AS prior_week_compliance_pct
        FROM v_weekly_kpi_by_service cur
        LEFT JOIN v_weekly_kpi_by_service prev
               ON prev.service_type = cur.service_type AND prev.week_ending = :p
        WHERE cur.week_ending = :w
        ORDER BY cur.breached_tickets DESC, cur.service_type
        """,
        w=week_ending,
        p=prior_week,
    )
    as_of = datetime.combine(week_ending + timedelta(days=1), datetime.min.time(), tzinfo=UTC)
    open_tickets = _query(
        engine,
        "SELECT * FROM f_open_tickets(:as_of) ORDER BY probability DESC NULLS LAST, creation_ts",
        as_of=as_of,
    )
    for col in ("creation_ts", "expected_resolution_ts"):
        open_tickets[col] = _to_naive_utc(open_tickets[col])
    at_risk = open_tickets[open_tickets["probability"].notna()].head(top_n).reset_index(drop=True)

    meta = _query(engine, "SELECT max(snapshot_ts) AS snapshot_ts FROM load_run")
    snapshot_ts = pd.Timestamp(meta["snapshot_ts"].iloc[0]).to_pydatetime()
    mv = _query(engine, "SELECT min(model_version) AS v FROM ticket_risk_score")["v"].iloc[0]
    url = engine.url.render_as_string(hide_password=True)
    return ReportData(
        week_ending=week_ending,
        week_start=week_ending - timedelta(days=6),
        as_of=as_of.replace(tzinfo=None),
        trend=trend,
        by_customer=by_customer,
        by_service=by_service,
        open_tickets=open_tickets,
        at_risk=at_risk,
        snapshot_ts=snapshot_ts,
        model_version=None if mv is None or pd.isna(mv) else str(mv),
        generated_at=datetime.now(UTC),
        source=f"PostgreSQL {url}",
    )


# ------------------------------------------------------------------------------------------
# Workbook helpers
# ------------------------------------------------------------------------------------------
def _v(value: Any) -> Any:
    """A pandas/DB value as something openpyxl writes cleanly (None for missing)."""
    if value is None:
        return None
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, pd.Timestamp):
        return value.to_pydatetime()
    if isinstance(value, float | int | str | bool | datetime | date):
        if isinstance(value, float) and pd.isna(value):
            return None
        return value
    if hasattr(value, "item"):  # numpy scalar
        return value.item()
    if pd.isna(value):
        return None
    return value


def _pct(value: Any) -> float | None:
    """A 0-100 percentage from the views as an Excel fraction (0-1)."""
    v = _v(value)
    return None if v is None else round(v / 100.0, 6)


def _title(ws: Worksheet, title: str, subtitle: str, banner: str = SYNTHETIC_BANNER) -> None:
    ws["A1"] = title
    ws["A1"].font = TITLE_FONT
    ws["A2"] = subtitle
    ws["A2"].font = SUBTITLE_FONT
    ws["A3"] = banner
    ws["A3"].font = BANNER_FONT


def _header(ws: Worksheet, row: int, labels: list[str], col: int = 1) -> None:
    for i, label in enumerate(labels):
        c = ws.cell(row=row, column=col + i, value=label)
        c.font = HEADER_FONT
        c.fill = HEADER_FILL
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        c.border = BOX
    ws.row_dimensions[row].height = 30


def _widths(ws: Worksheet, widths: dict[str, float]) -> None:
    for col, w in widths.items():
        ws.column_dimensions[col].width = w


def _style_row(ws: Worksheet, row: int, first_col: int, last_col: int, **kw: Any) -> None:
    for col in range(first_col, last_col + 1):
        c = ws.cell(row=row, column=col)
        for k, val in kw.items():
            setattr(c, k, val)
        c.border = BOX


def _delta_formatting(ws: Worksheet, cell_range: str, higher_is_better: bool) -> None:
    up, down = (GOOD_FILL, GOOD_FONT), (BAD_FILL, BAD_FONT)
    if not higher_is_better:
        up, down = down, up
    ws.conditional_formatting.add(
        cell_range, CellIsRule(operator="greaterThan", formula=["0"], fill=up[0], font=up[1])
    )
    ws.conditional_formatting.add(
        cell_range, CellIsRule(operator="lessThan", formula=["0"], fill=down[0], font=down[1])
    )


def _sum_row(
    ws: Worksheet,
    row: int,
    first_data_row: int,
    last_data_row: int,
    cols: list[int],
    label_col: int = 1,
    label: str = "Total",
) -> None:
    ws.cell(row=row, column=label_col, value=label)
    for col in cols:
        letter = get_column_letter(col)
        ws.cell(
            row=row, column=col, value=f"=SUM({letter}{first_data_row}:{letter}{last_data_row})"
        )


# ------------------------------------------------------------------------------------------
# Sheets
# ------------------------------------------------------------------------------------------
# (label, trend column, number format, delta format, higher_is_better or None for neutral)
KPI_ROWS: list[tuple[str, str, str, str, bool | None]] = [
    ("Tickets opened", "tickets_opened", FMT_INT, FMT_DELTA_INT, None),
    ("Tickets resolved", "tickets_resolved", FMT_INT, FMT_DELTA_INT, True),
    ("SLA compliance", "sla_compliance", FMT_PCT, FMT_PP, True),
    ("SLA breaches", "breached_tickets", FMT_INT, FMT_DELTA_INT, False),
    ("MTTR - mean resolution (h)", "mttr_hours", FMT_HOURS, FMT_DELTA_HOURS, False),
    ("Resolution time p50 (h)", "p50_resolution_hours", FMT_HOURS, FMT_DELTA_HOURS, False),
    ("Resolution time p90 (h)", "p90_resolution_hours", FMT_HOURS, FMT_DELTA_HOURS, False),
    ("Open backlog at week end", "open_backlog", FMT_INT, FMT_DELTA_INT, False),
    ("Backlog aged over the SLA (past due)", "backlog_past_due", FMT_INT, FMT_DELTA_INT, False),
    ("High-risk open tickets (model)", "high_risk_open", FMT_INT, FMT_DELTA_INT, False),
]
TREND_COLUMNS: list[tuple[str, str, str]] = [
    ("Week ending", "week_ending", FMT_DATE),
    ("Opened", "tickets_opened", FMT_INT),
    ("Resolved", "tickets_resolved", FMT_INT),
    ("Breaches", "breached_tickets", FMT_INT),
    ("SLA compliance", "sla_compliance", FMT_PCT),  # formula
    ("MTTR (h)", "mttr_hours", FMT_HOURS),
    ("p50 (h)", "p50_resolution_hours", FMT_HOURS),
    ("p90 (h)", "p90_resolution_hours", FMT_HOURS),
    ("Open backlog", "open_backlog", FMT_INT),
    ("Past due", "backlog_past_due", FMT_INT),
    ("High-risk open", "high_risk_open", FMT_INT),
]
SUMMARY_KPI_HEADER_ROW = 5
SUMMARY_TREND_HEADER_ROW = SUMMARY_KPI_HEADER_ROW + len(KPI_ROWS) + 4  # 19


def _summary_sheet(wb: Workbook, d: ReportData) -> None:
    ws = wb.active
    ws.title = "Summary"
    n = len(d.trend)
    trend_first = SUMMARY_TREND_HEADER_ROW + 1
    trend_last = SUMMARY_TREND_HEADER_ROW + n
    report_row = trend_last
    prior_row = trend_last - 1
    base_first = max(trend_first, trend_last - BASELINE_WEEKS)
    base_last = trend_last - 1
    base_weeks = base_last - base_first + 1
    base_start = d.week_ending - timedelta(days=7 * base_weeks)
    base_end = d.week_ending - timedelta(days=7)

    _title(
        ws,
        f"Weekly service-desk KPI report - week ending {d.week_ending.isoformat()}",
        f"Monday {d.week_start.isoformat()} to Sunday {d.week_ending.isoformat()} (UTC). "
        f"Prior week ends {base_end.isoformat()}; trailing {base_weeks}-week average covers "
        f"the weeks ending {base_start.isoformat()} to {base_end.isoformat()}. "
        f"Backlog measured at {d.as_of.isoformat(sep=' ')} UTC.",
    )

    # KPI tiles: live references into the trend table below.
    _header(
        ws,
        SUMMARY_KPI_HEADER_ROW,
        [
            "KPI",
            "This week",
            "Prior week",
            "Change vs prior",
            f"Trailing {base_weeks}-wk avg",
            f"Change vs {base_weeks}-wk avg",
            "Better when",
        ],
    )
    col_of = {key: i + 1 for i, (_, key, _) in enumerate(TREND_COLUMNS)}
    for i, (label, key, fmt, dfmt, higher_better) in enumerate(KPI_ROWS):
        r = SUMMARY_KPI_HEADER_ROW + 1 + i
        L = get_column_letter(col_of[key])
        ws.cell(row=r, column=1, value=label)
        ws.cell(row=r, column=2, value=f"={L}{report_row}")
        ws.cell(row=r, column=3, value=f"={L}{prior_row}")
        ws.cell(row=r, column=4, value=f"=B{r}-C{r}")
        ws.cell(row=r, column=5, value=f"=AVERAGE({L}{base_first}:{L}{base_last})")
        ws.cell(row=r, column=6, value=f"=B{r}-E{r}")
        ws.cell(row=r, column=7, value={True: "higher", False: "lower", None: "-"}[higher_better])
        for col in (2, 3, 5):
            ws.cell(row=r, column=col).number_format = fmt
        for col in (4, 6):
            ws.cell(row=r, column=col).number_format = dfmt if fmt != FMT_PCT else FMT_PP
        if fmt == FMT_PCT:
            # deltas of a fraction shown as percentage points
            ws.cell(row=r, column=4, value=f"=(B{r}-C{r})*100")
            ws.cell(row=r, column=6, value=f"=(B{r}-E{r})*100")
        _style_row(ws, r, 1, 7)
        ws.cell(row=r, column=1).font = Font(bold=True)
        ws.cell(row=r, column=7).alignment = Alignment(horizontal="center")
        if higher_better is not None:
            _delta_formatting(ws, f"D{r}:D{r}", higher_better)
            _delta_formatting(ws, f"F{r}:F{r}", higher_better)

    # Trend table (values from v_weekly_kpi; compliance is a formula).
    ws.cell(
        row=SUMMARY_TREND_HEADER_ROW - 1,
        column=1,
        value=f"Weekly trend - last {n} full weeks (report week last)",
    ).font = Font(bold=True)
    _header(ws, SUMMARY_TREND_HEADER_ROW, [label for label, _, _ in TREND_COLUMNS])
    for i, row in enumerate(d.trend.itertuples(index=False)):
        r = trend_first + i
        for j, (_, key, fmt) in enumerate(TREND_COLUMNS):
            col = j + 1
            if key == "sla_compliance":
                value = f'=IFERROR(1-D{r}/C{r},"")'
            elif key == "week_ending":
                value = pd.Timestamp(getattr(row, key)).to_pydatetime()
            else:
                value = _v(getattr(row, key))
            c = ws.cell(row=r, column=col, value=value)
            c.number_format = fmt
            c.border = BOX
        if r == report_row:
            _style_row(ws, r, 1, len(TREND_COLUMNS), fill=TOTAL_FILL, font=TOTAL_FONT)
    ws.conditional_formatting.add(
        f"E{trend_first}:E{trend_last}",
        ColorScaleRule(
            start_type="min",
            start_color="F8696B",
            mid_type="percentile",
            mid_value=50,
            mid_color="FFEB84",
            end_type="max",
            end_color="63BE7B",
        ),
    )
    ws.conditional_formatting.add(
        f"I{trend_first}:I{trend_last}",
        DataBarRule(start_type="min", end_type="max", color="5B9BD5"),
    )

    # Charts over the trend table.
    line = LineChart()
    line.title = "SLA compliance by week (synthetic data)"
    line.y_axis.title = "Compliance"
    line.y_axis.number_format = "0%"
    line.x_axis.number_format = FMT_DATE
    line.x_axis.title = "Week ending"
    line.x_axis.delete = False
    line.y_axis.delete = False
    line.add_data(
        Reference(ws, min_col=5, min_row=SUMMARY_TREND_HEADER_ROW, max_row=trend_last),
        titles_from_data=True,
    )
    line.set_categories(Reference(ws, min_col=1, min_row=trend_first, max_row=trend_last))
    line.height, line.width = 7.5, 16
    ws.add_chart(line, "I5")

    bars = BarChart()
    bars.type = "col"
    bars.grouping = "clustered"
    bars.title = "Tickets opened vs resolved by week (synthetic data)"
    bars.x_axis.number_format = FMT_DATE
    bars.x_axis.delete = False
    bars.y_axis.delete = False
    bars.y_axis.number_format = FMT_INT
    bars.add_data(
        Reference(ws, min_col=2, max_col=3, min_row=SUMMARY_TREND_HEADER_ROW, max_row=trend_last),
        titles_from_data=True,
    )
    bars.set_categories(Reference(ws, min_col=1, min_row=trend_first, max_row=trend_last))
    bars.height, bars.width = 7.5, 16
    ws.add_chart(bars, "I21")

    ws.freeze_panes = ws.cell(row=SUMMARY_KPI_HEADER_ROW + 1, column=1)
    _widths(
        ws,
        {
            "A": 38,
            "B": 13,
            "C": 13,
            "D": 15,
            "E": 16,
            "F": 18,
            "G": 12,
            "H": 3,
            "I": 12,
            "J": 12,
            "K": 12,
        },
    )


def _open_aggregates(open_tickets: pd.DataFrame, key: str) -> pd.DataFrame:
    if open_tickets.empty:
        return pd.DataFrame(columns=[key, "open_backlog", "backlog_past_due", "high_risk_open"])
    g = open_tickets.groupby(key)
    return pd.DataFrame(
        {
            "open_backlog": g.size(),
            "backlog_past_due": g["past_due"].sum().astype(int),
            "high_risk_open": g["risk_band"].apply(lambda s: int((s == "high").sum())),
        }
    ).reset_index()


def _by_customer_sheet(wb: Workbook, d: ReportData) -> None:
    ws = wb.create_sheet("By customer")
    _title(
        ws,
        f"By customer - week ending {d.week_ending.isoformat()}",
        "Opened, resolved and breaches for the week; backlog and the model's high-risk open "
        f"tickets at {d.as_of.isoformat(sep=' ')} UTC. Sorted by breaches.",
    )
    labels = [
        "Customer",
        "Tier",
        "Industry",
        "Opened",
        "Resolved",
        "Breaches",
        "SLA compliance",
        "Prior week compliance",
        "Change (pp)",
        "p50 resolution (h)",
        "Open backlog",
        "Past due",
        "High-risk open (model)",
    ]
    hdr = 5
    _header(ws, hdr, labels)
    agg = _open_aggregates(d.open_tickets, "customer_id")
    df = d.by_customer.merge(agg, on="customer_id", how="left").fillna(
        {"open_backlog": 0, "backlog_past_due": 0, "high_risk_open": 0}
    )
    first = hdr + 1
    for i, row in enumerate(df.itertuples(index=False)):
        r = first + i
        ws.cell(row=r, column=1, value=row.customer_name)
        ws.cell(row=r, column=2, value=str(row.tier).title())
        ws.cell(row=r, column=3, value=str(row.industry).replace("_", " ").title())
        ws.cell(row=r, column=4, value=_v(row.tickets_opened)).number_format = FMT_INT
        ws.cell(row=r, column=5, value=_v(row.tickets_resolved)).number_format = FMT_INT
        ws.cell(row=r, column=6, value=_v(row.breached_tickets)).number_format = FMT_INT
        ws.cell(row=r, column=7, value=f'=IFERROR(1-F{r}/E{r},"")').number_format = FMT_PCT
        ws.cell(row=r, column=8, value=_pct(row.prior_week_compliance_pct)).number_format = FMT_PCT
        ws.cell(row=r, column=9, value=f'=IFERROR((G{r}-H{r})*100,"")').number_format = FMT_PP
        ws.cell(row=r, column=10, value=_v(row.p50_resolution_hours)).number_format = FMT_HOURS
        ws.cell(row=r, column=11, value=int(row.open_backlog)).number_format = FMT_INT
        ws.cell(row=r, column=12, value=int(row.backlog_past_due)).number_format = FMT_INT
        ws.cell(row=r, column=13, value=int(row.high_risk_open)).number_format = FMT_INT
        _style_row(ws, r, 1, len(labels))
    last = first + len(df) - 1
    total = last + 1
    _sum_row(ws, total, first, last, [4, 5, 6, 11, 12, 13])
    ws.cell(row=total, column=7, value=f'=IFERROR(1-F{total}/E{total},"")').number_format = FMT_PCT
    _style_row(ws, total, 1, len(labels), fill=TOTAL_FILL, font=TOTAL_FONT)
    for col in (4, 5, 6, 11, 12, 13):
        ws.cell(row=total, column=col).number_format = FMT_INT
    ws.conditional_formatting.add(
        f"G{first}:G{last}",
        ColorScaleRule(
            start_type="num",
            start_value=0.7,
            start_color="F8696B",
            mid_type="num",
            mid_value=0.85,
            mid_color="FFEB84",
            end_type="num",
            end_value=1,
            end_color="63BE7B",
        ),
    )
    _delta_formatting(ws, f"I{first}:I{last}", higher_is_better=True)
    ws.conditional_formatting.add(
        f"M{first}:M{last}",
        DataBarRule(start_type="num", start_value=0, end_type="max", color="C00000"),
    )
    ws.conditional_formatting.add(
        f"K{first}:K{last}",
        DataBarRule(start_type="num", start_value=0, end_type="max", color="5B9BD5"),
    )
    ws.freeze_panes = ws.cell(row=first, column=2)
    ws.auto_filter.ref = f"A{hdr}:{get_column_letter(len(labels))}{last}"
    _widths(
        ws,
        {
            "A": 32,
            "B": 10,
            "C": 20,
            "D": 9,
            "E": 9,
            "F": 9,
            "G": 12,
            "H": 12,
            "I": 11,
            "J": 12,
            "K": 11,
            "L": 9,
            "M": 14,
        },
    )


def _by_service_sheet(wb: Workbook, d: ReportData) -> None:
    ws = wb.create_sheet("By service")
    _title(
        ws,
        f"By service type - week ending {d.week_ending.isoformat()}",
        "Resolution-week basis for compliance and the percentiles; backlog at "
        f"{d.as_of.isoformat(sep=' ')} UTC.",
    )
    labels = [
        "Service type",
        "Opened",
        "Resolved",
        "Breaches",
        "SLA compliance",
        "Prior week compliance",
        "Change (pp)",
        "p50 (h)",
        "p90 (h)",
        "Open backlog",
        "Past due",
        "High-risk open (model)",
    ]
    hdr = 5
    _header(ws, hdr, labels)
    agg = _open_aggregates(d.open_tickets, "service_type")
    df = d.by_service.merge(agg, on="service_type", how="left").fillna(
        {"open_backlog": 0, "backlog_past_due": 0, "high_risk_open": 0}
    )
    first = hdr + 1
    for i, row in enumerate(df.itertuples(index=False)):
        r = first + i
        ws.cell(row=r, column=1, value=SERVICE_LABELS.get(row.service_type, row.service_type))
        ws.cell(row=r, column=2, value=_v(row.tickets_opened)).number_format = FMT_INT
        ws.cell(row=r, column=3, value=_v(row.tickets_resolved)).number_format = FMT_INT
        ws.cell(row=r, column=4, value=_v(row.breached_tickets)).number_format = FMT_INT
        ws.cell(row=r, column=5, value=f'=IFERROR(1-D{r}/C{r},"")').number_format = FMT_PCT
        ws.cell(row=r, column=6, value=_pct(row.prior_week_compliance_pct)).number_format = FMT_PCT
        ws.cell(row=r, column=7, value=f'=IFERROR((E{r}-F{r})*100,"")').number_format = FMT_PP
        ws.cell(row=r, column=8, value=_v(row.p50_resolution_hours)).number_format = FMT_HOURS
        ws.cell(row=r, column=9, value=_v(row.p90_resolution_hours)).number_format = FMT_HOURS
        ws.cell(row=r, column=10, value=int(row.open_backlog)).number_format = FMT_INT
        ws.cell(row=r, column=11, value=int(row.backlog_past_due)).number_format = FMT_INT
        ws.cell(row=r, column=12, value=int(row.high_risk_open)).number_format = FMT_INT
        _style_row(ws, r, 1, len(labels))
    last = first + len(df) - 1
    total = last + 1
    _sum_row(ws, total, first, last, [2, 3, 4, 10, 11, 12])
    ws.cell(row=total, column=5, value=f'=IFERROR(1-D{total}/C{total},"")').number_format = FMT_PCT
    _style_row(ws, total, 1, len(labels), fill=TOTAL_FILL, font=TOTAL_FONT)
    for col in (2, 3, 4, 10, 11, 12):
        ws.cell(row=total, column=col).number_format = FMT_INT
    ws.conditional_formatting.add(
        f"E{first}:E{last}",
        ColorScaleRule(
            start_type="num",
            start_value=0.7,
            start_color="F8696B",
            mid_type="num",
            mid_value=0.85,
            mid_color="FFEB84",
            end_type="num",
            end_value=1,
            end_color="63BE7B",
        ),
    )
    _delta_formatting(ws, f"G{first}:G{last}", higher_is_better=True)

    chart = BarChart()
    chart.type = "bar"
    chart.title = "SLA breaches by service type (synthetic data)"
    chart.x_axis.delete = False
    chart.y_axis.delete = False
    chart.add_data(Reference(ws, min_col=4, min_row=hdr, max_row=last), titles_from_data=True)
    chart.set_categories(Reference(ws, min_col=1, min_row=first, max_row=last))
    chart.legend = None
    chart.height, chart.width = 7, 14
    ws.add_chart(chart, f"A{total + 3}")

    ws.freeze_panes = ws.cell(row=first, column=2)
    _widths(
        ws,
        {
            "A": 24,
            "B": 9,
            "C": 9,
            "D": 9,
            "E": 12,
            "F": 12,
            "G": 11,
            "H": 9,
            "I": 9,
            "J": 11,
            "K": 9,
            "L": 14,
        },
    )


def _ageing_block(
    ws: Worksheet, d: ReportData, key: str, label: str, start_row: int, labeller=lambda s: s
) -> tuple[int, int, int]:
    """One age-band matrix (rows = key values). Returns (header_row, first, last)."""
    labels = [
        label,
        *AGE_BUCKETS,
        "Total open",
        "Past due",
        "Critical or major",
        "High-risk (model)",
        "Median age (h)",
    ]
    ws.cell(row=start_row - 1, column=1, value=f"Open tickets by {label.lower()} and age band")
    ws.cell(row=start_row - 1, column=1).font = Font(bold=True)
    _header(ws, start_row, labels)
    ot = d.open_tickets
    keys = sorted(ot[key].unique()) if not ot.empty else []
    first = start_row + 1
    for i, k in enumerate(keys):
        r = first + i
        sub = ot[ot[key] == k]
        counts = sub["age_bucket"].value_counts()
        ws.cell(row=r, column=1, value=labeller(k))
        for j, bucket in enumerate(AGE_BUCKETS):
            ws.cell(row=r, column=2 + j, value=int(counts.get(bucket, 0))).number_format = FMT_INT
        ws.cell(row=r, column=7, value=f"=SUM(B{r}:F{r})").number_format = FMT_INT
        ws.cell(row=r, column=8, value=int(sub["past_due"].sum())).number_format = FMT_INT
        ws.cell(
            row=r, column=9, value=int(sub["severity"].isin(["critical", "major"]).sum())
        ).number_format = FMT_INT
        ws.cell(
            row=r, column=10, value=int((sub["risk_band"] == "high").sum())
        ).number_format = FMT_INT
        ws.cell(
            row=r, column=11, value=round(float(sub["age_hours"].astype(float).median()), 1)
        ).number_format = FMT_HOURS
        _style_row(ws, r, 1, len(labels))
    last = first + max(len(keys), 1) - 1
    total = last + 1
    _sum_row(ws, total, first, last, list(range(2, 11)))
    ws.cell(
        row=total,
        column=11,
        value=round(float(ot["age_hours"].astype(float).median()), 1) if not ot.empty else None,
    )
    ws.cell(row=total, column=11).number_format = FMT_HOURS
    _style_row(ws, total, 1, len(labels), fill=TOTAL_FILL, font=TOTAL_FONT)
    for col in range(2, 11):
        ws.cell(row=total, column=col).number_format = FMT_INT
    ws.conditional_formatting.add(
        f"H{first}:H{last}",
        DataBarRule(start_type="num", start_value=0, end_type="max", color="C00000"),
    )
    return start_row, first, last


def _backlog_sheet(wb: Workbook, d: ReportData) -> None:
    ws = wb.create_sheet("Backlog ageing")
    _title(
        ws,
        f"Backlog ageing at {d.as_of.isoformat(sep=' ')} UTC (end of week {d.week_ending})",
        "Age = time since creation at the snapshot. Past due = already beyond the expected "
        "resolution date. Row totals are formulas.",
    )
    hdr1, first1, last1 = _ageing_block(
        ws, d, "assignment_group", "Assignment group", 6, labeller=group_label
    )
    hdr2, first2, last2 = _ageing_block(
        ws,
        d,
        "service_type",
        "Service type",
        last1 + 5,
        labeller=lambda s: SERVICE_LABELS.get(s, s),
    )
    chart = BarChart()
    chart.type = "col"
    chart.grouping = "stacked"
    chart.overlap = 100
    chart.title = "Open tickets by assignment group and age band (synthetic data)"
    chart.x_axis.delete = False
    chart.y_axis.delete = False
    chart.add_data(
        Reference(ws, min_col=2, max_col=6, min_row=hdr1, max_row=last1), titles_from_data=True
    )
    chart.set_categories(Reference(ws, min_col=1, min_row=first1, max_row=last1))
    chart.height, chart.width = 8, 16
    ws.add_chart(chart, f"A{last2 + 5}")
    ws.freeze_panes = "B7"
    _widths(
        ws,
        {
            "A": 24,
            "B": 8,
            "C": 8,
            "D": 8,
            "E": 8,
            "F": 8,
            "G": 11,
            "H": 10,
            "I": 16,
            "J": 16,
            "K": 14,
        },
    )


def _at_risk_sheet(wb: Workbook, d: ReportData) -> None:
    ws = wb.create_sheet("At-risk open tickets")
    n = len(d.at_risk)
    _title(
        ws,
        f"Top {n} open tickets by predicted SLA-breach probability",
        f"Open at the end of week {d.week_ending}; probability from model "
        f"{d.model_version or 'n/a'} using creation-time features only. Age and past-due are "
        "formulas against the snapshot in B4.",
    )
    ws["A4"] = "Snapshot (UTC)"
    ws["A4"].font = Font(bold=True)
    ws["B4"] = d.as_of
    ws["B4"].number_format = FMT_DATETIME
    labels = [
        "Rank",
        "Ticket",
        "Title",
        "Customer",
        "Tier",
        "Service type",
        "Severity",
        "Assignment group",
        "Created (UTC)",
        "Age (h)",
        "SLA target (h)",
        "Expected resolution (UTC)",
        "Past due",
        "Breach probability",
        "Risk band",
    ]
    hdr = 6
    _header(ws, hdr, labels)
    first = hdr + 1
    for i, row in enumerate(d.at_risk.itertuples(index=False)):
        r = first + i
        ws.cell(row=r, column=1, value=i + 1)
        ws.cell(row=r, column=2, value=row.ticket_id)
        ws.cell(row=r, column=3, value=row.name)
        ws.cell(row=r, column=4, value=row.customer_name)
        ws.cell(row=r, column=5, value=str(row.tier).title())
        ws.cell(row=r, column=6, value=SERVICE_LABELS.get(row.service_type, row.service_type))
        ws.cell(row=r, column=7, value=str(row.severity).title())
        ws.cell(row=r, column=8, value=group_label(row.assignment_group))
        ws.cell(row=r, column=9, value=_v(row.creation_ts)).number_format = FMT_DATETIME
        ws.cell(row=r, column=10, value=f"=ROUND(($B$4-I{r})*24,1)").number_format = FMT_HOURS
        ws.cell(row=r, column=11, value=_v(row.sla_target_hours)).number_format = FMT_HOURS
        ws.cell(row=r, column=12, value=_v(row.expected_resolution_ts)).number_format = FMT_DATETIME
        ws.cell(row=r, column=13, value=f'=IF($B$4>L{r},"yes","no")')
        ws.cell(row=r, column=14, value=_v(row.probability)).number_format = FMT_PROB
        ws.cell(row=r, column=15, value=str(row.risk_band))
        _style_row(ws, r, 1, len(labels))
    last = first + max(n, 1) - 1
    ws.conditional_formatting.add(
        f"N{first}:N{last}",
        ColorScaleRule(
            start_type="num",
            start_value=0,
            start_color="FFFFFF",
            end_type="num",
            end_value=1,
            end_color="C00000",
        ),
    )
    ws.conditional_formatting.add(
        f"M{first}:M{last}",
        CellIsRule(operator="equal", formula=['"yes"'], fill=BAD_FILL, font=BAD_FONT),
    )
    ws.freeze_panes = ws.cell(row=first, column=3)
    ws.auto_filter.ref = f"A{hdr}:{get_column_letter(len(labels))}{last}"
    _widths(
        ws,
        {
            "A": 6,
            "B": 12,
            "C": 32,
            "D": 30,
            "E": 9,
            "F": 20,
            "G": 9,
            "H": 16,
            "I": 17,
            "J": 8,
            "K": 12,
            "L": 22,
            "M": 9,
            "N": 12,
            "O": 9,
        },
    )


def _notes_sheet(wb: Workbook, d: ReportData) -> None:
    ws = wb.create_sheet("Notes")
    ws["A1"] = "Notes, definitions and provenance"
    ws["A1"].font = TITLE_FONT
    ws["A3"] = "SYNTHETIC DATA"
    ws["A3"].font = Font(bold=True, size=12, color="9C0006")
    ws["B3"] = (
        "Every customer, site, service, outage and ticket in this workbook was generated by "
        "slawatch from a seed. Nothing here describes a real company, network or ticket system."
    )
    rows = [
        ("Generated at (UTC)", d.generated_at.replace(microsecond=0).isoformat()),
        ("Generator", f"slawatch-report {__version__} (openpyxl)"),
        ("Data source", d.source),
        (
            "Views used",
            "v_weekly_kpi, v_weekly_kpi_by_customer, v_weekly_kpi_by_service, "
            "f_open_tickets(as_of) - see sql/views/20_backlog_ageing.sql and "
            "sql/views/70_weekly_kpi.sql",
        ),
        (
            "Load snapshot (UTC)",
            d.snapshot_ts.astimezone(UTC).replace(tzinfo=None).isoformat(sep=" "),
        ),
        ("Report week", f"Monday {d.week_start} 00:00 to Sunday {d.week_ending} 24:00 UTC"),
        ("Backlog snapshot", f"{d.as_of.isoformat(sep=' ')} UTC (the Monday after the week)"),
        ("Model version", d.model_version or "no risk scores loaded (run make train)"),
        ("", ""),
        ("Definitions", ""),
        (
            "Tickets opened",
            "Tickets created during the week. Cancelled tickets are excluded from "
            "every figure in this workbook.",
        ),
        (
            "Tickets resolved",
            "Tickets whose final resolution falls in the week (reopened tickets "
            "count at their last resolution).",
        ),
        (
            "SLA compliance",
            "1 - breaches / resolved, on the tickets resolved in the week "
            "(resolution-week basis), so the latest week is never an unfinished "
            "cohort. A breach is a final resolution after the contracted target "
            "for the customer tier x severity.",
        ),
        ("SLA breaches", "Resolved-in-week tickets whose resolution time exceeded the target."),
        (
            "MTTR / p50 / p90",
            "Mean, median and 90th percentile of resolution hours over the "
            "tickets resolved in the week.",
        ),
        (
            "Open backlog",
            "Tickets created at or before the backlog snapshot and not yet resolved "
            "or cancelled at that moment (same rule as f_backlog_ageing).",
        ),
        (
            "Backlog aged over the SLA",
            "Open tickets already past their expected resolution date "
            "at the snapshot ('past due').",
        ),
        ("Age bands", "0-24h, 1-3d, 3-7d, 7-30d, 30d+ of elapsed time since creation."),
        (
            "High-risk open (model)",
            "Open tickets whose predicted breach probability falls in the "
            "model's 'high' band (the top ~10% of validation-period risk).",
        ),
        (
            "Breach probability",
            "P(SLA breach) from the committed scikit-learn classifier, using "
            "only information available when the ticket was opened.",
        ),
        (
            "Prior week / trailing average",
            "Prior week = the week before the report week. The "
            "trailing average is the mean of the four weeks before "
            "the report week (fewer if the data starts later).",
        ),
        (
            "Formulas",
            "Summary tiles, deltas, averages, compliance, totals, age and past-due "
            "columns are Excel formulas; the remaining cells hold values copied from "
            "the views.",
        ),
        ("Timezone", "All timestamps are UTC."),
    ]
    for i, (k, v) in enumerate(rows):
        r = 5 + i
        ws.cell(row=r, column=1, value=k).font = Font(bold=True)
        c = ws.cell(row=r, column=2, value=v)
        c.alignment = Alignment(wrap_text=True, vertical="top")
    ws["A14"].font = Font(bold=True, size=12)
    _widths(ws, {"A": 30, "B": 110})


def build_workbook(d: ReportData) -> Workbook:
    wb = Workbook()
    wb.properties.title = (
        f"Weekly service-desk KPI report - week ending {d.week_ending} (synthetic data)"
    )
    wb.properties.subject = "SYNTHETIC DATA generated by slawatch"
    wb.properties.creator = f"slawatch-report {__version__}"
    wb.properties.description = SYNTHETIC_BANNER
    _summary_sheet(wb, d)
    _by_customer_sheet(wb, d)
    _by_service_sheet(wb, d)
    _backlog_sheet(wb, d)
    _at_risk_sheet(wb, d)
    _notes_sheet(wb, d)
    return wb


def default_out_path(week_ending: date, reports_dir: Path = DEFAULT_REPORTS_DIR) -> Path:
    return reports_dir / f"synthetic_weekly_kpi_{week_ending.isoformat()}.xlsx"


def write_report(
    engine: Engine,
    week_ending: date | None = None,
    out: Path | None = None,
    top_n: int = DEFAULT_TOP_N,
    reports_dir: Path = DEFAULT_REPORTS_DIR,
) -> tuple[Path, ReportData]:
    data = fetch(engine, week_ending, top_n=top_n)
    out = out or default_out_path(data.week_ending, reports_dir)
    out.parent.mkdir(parents=True, exist_ok=True)
    build_workbook(data).save(out)
    log.info("wrote %s (week ending %s, %d at-risk rows)", out, data.week_ending, len(data.at_risk))
    return out, data


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Weekly KPI report (.xlsx) from the slawatch views.")
    p.add_argument(
        "--week-ending",
        type=parse_week_ending,
        default=None,
        help="Sunday, YYYY-MM-DD (default: the last full week in the data)",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output .xlsx (default: <out-dir>/synthetic_weekly_kpi_<week>.xlsx)",
    )
    p.add_argument(
        "--out-dir",
        type=Path,
        default=DEFAULT_REPORTS_DIR,
        help="directory for the default file name",
    )
    p.add_argument("--top-n", type=int, default=DEFAULT_TOP_N, help="rows on the at-risk sheet")
    p.add_argument("--database-url", default=None, help="defaults to $DATABASE_URL")
    return p


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(message)s")
    args = build_parser().parse_args(argv)
    engine = db.get_engine(args.database_url)
    out, data = write_report(
        engine, args.week_ending, args.out, top_n=args.top_n, reports_dir=args.out_dir
    )
    t = data.trend.iloc[-1]
    log.info(
        "week ending %s: opened %d, resolved %d, compliance %.2f%%, breaches %d, "
        "p50 %.1f h, p90 %.1f h, backlog %d (%d past due, %d high-risk)",
        data.week_ending,
        t.tickets_opened,
        t.tickets_resolved,
        t.sla_compliance_pct,
        t.breached_tickets,
        t.p50_resolution_hours,
        t.p90_resolution_hours,
        t.open_backlog,
        t.backlog_past_due,
        t.high_risk_open,
    )
    print(out)


if __name__ == "__main__":
    main()
